# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rehan Butt
email: me@rehanbutt.com
year: 2022
description: > # this means to ignore newlines until "baseurl:"
  As we close out 2022, let's take a look at all that has happened. I left Pittsburgh, a city I called home for the last decade, and the world of healthcare technology. I joined Hollywood and the animation industry, attended some amazing events including the World Expo and my first Wrap Party and continued to ship some awesome new software products.

baseurl: "" # the subpath of your site, e.g. /blog
mainurl: "https://rehanbutt.com"
url: "https://2022.rehanbutt.com" # the base hostname & protocol for your site
keywords: >
  year in review,2022,yearly recap,devzgn,devzgner,personal review, personal recap,recap 2022,Design,UX,UI,webdev,branding,portfolio,site

# Build settings
markdown: kramdown

plugins: [jekyll-sitemap]

collections:
  songs:
    output: false